#!/usr/bin/env ruby

$:<< File.expand_path('../../app/workers',  __FILE__)

require 'rufus/scheduler'
require 'sidekiq'
require 'ping_url'
require 'yaml'
require 'erb'

# Configure sidekiq
Sidekiq.configure_server do |config|
  config.redis = Yaml.load(
    ERB.new(
      File.read(File.join(File.dirname(__FILE__), '../config/sidekiq_config.yml'))
    ).result
  )[ENV[RACK_ENV]]
end

scheduler = Rufus::Scheduler.start_new

scheduler.every '1m' do
  PingUrl.perform_async
end

scheduler.join
